# Generated by Django 2.1.7 on 2019-06-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190626_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cerificate',
            name='AfterDate',
            field=models.BigIntegerField(null=True, verbose_name='AfterDate'),
        ),
        migrations.AlterField(
            model_name='cerificate',
            name='BeforeDate',
            field=models.BigIntegerField(null=True, verbose_name='BeforeDate'),
        ),
        migrations.AlterField(
            model_name='cerificate',
            name='Comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='cerificate',
            name='Name',
            field=models.CharField(max_length=128, null=True, verbose_name='CerificateName'),
        ),
        migrations.AlterField(
            model_name='cerificate',
            name='ProdInvalidDate',
            field=models.DateTimeField(null=True, verbose_name='ProdInvalidDate'),
        ),
        migrations.AlterField(
            model_name='cerificate',
            name='ProdInvalidDays',
            field=models.IntegerField(null=True, verbose_name='ProdInvalidDays'),
        ),
        migrations.AlterField(
            model_name='cerificate',
            name='RemainingDays',
            field=models.IntegerField(null=True, verbose_name='RemainingDays'),
        ),
        migrations.AlterField(
            model_name='cerificate',
            name='StatusCode',
            field=models.CharField(max_length=16, null=True, verbose_name='StatusCode'),
        ),
        migrations.AlterField(
            model_name='cerificate',
            name='Year',
            field=models.IntegerField(null=True, verbose_name='Year'),
        ),
    ]
