# CMDB系统配置段
cmdb:
  host: 0.0.0.0
  port: 8000
  base_url: http://127.0.0.1:8082
  daemon: false
  debug: true
  loglevel: DEBUG  #DEBUG INFO WARN ERROR
  
# REDIS配置段
redis:
  host: 172.16.0.13
  password: selktech
  port: 6379
  db: 8
# EMAIL配置段
email:
  host: 172.18.207.238
  port: 465
  username: dev@silktech.com
  password: Wubida@123
  tls: false

# LDAP配置段
ldap:
  enable: true
  host: ldap://172.16.0.13
  port: 389
  binddn: cn=admin,ou=SystemUser,dc=silktech,dc=com
  bindpassword: deakingP@ssw0rd
  basedn: dc=silktech,dc=com
  usersdn: ou=Users,dc=silktech,dc=com
  userfilter: '(&(uid=%(user)s))'
  userattrmap: 
    username: "uid"
    name: "sn"
    email: "mail"
    nickname: "sn"
    mobile: "mobile"
  mirror_groups: true
  groupsdn: ou=Groups,dc=silktech,dc=com
  cmdbpermissdn: ou=Cmdb,ou=Groups,dc=silktech,dc=com
  tls: false
# 阿里去配置段
aliyun:
  # 物必达
  wbd:
    name: '物必达(silktech)'
    accesskey: 'LTAIUWuSChF0IY7L'
    accesssecret: '9e1QiG9cRDTIGJnUcOQMK27C1ohu8v'
  # 94lazy
  lazy:
    name: '就是赖(94lazy)'
    accesskey: 'LTAIBsNvE3dgppCx'
    accesssecret: 'IBeSKdl1DdxbcqjoahXL1zB8m1196n'
