# Generated by Django 2.1.7 on 2019-07-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
