# Generated by Django 2.1.7 on 2019-04-08 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['username'], 'verbose_name': 'Users', 'verbose_name_plural': 'users'},
        ),
    ]
