# Generated by Django 2.1.7 on 2019-04-09 10:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20190408_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='secretkey',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='用户jwt加密秘钥'),
        ),
    ]
