# Generated by Django 2.1.7 on 2019-07-17 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_users_updatetime'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='users',
            unique_together={('username', 'userdn')},
        ),
    ]
