# Generated by Django 2.1.7 on 2019-07-17 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20190717_1708'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='users',
            unique_together=set(),
        ),
    ]
