# Generated by Django 2.1.7 on 2019-05-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20190520_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='memo',
        ),
        migrations.AddField(
            model_name='users',
            name='department',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='部门'),
        ),
        migrations.AddField(
            model_name='users',
            name='mobile',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='用户手机'),
        ),
        migrations.AddField(
            model_name='users',
            name='userdn',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='用户DN'),
        ),
        migrations.AlterField(
            model_name='users',
            name='nickname',
            field=models.TextField(blank=True, max_length=32, null=True, verbose_name='昵称'),
        ),
    ]
